name: Create netclient vendor tarball
on:
  push:
    branches:
    - main
    tags:
    - 'v**'
  pull_request:
    branches:
    - main

permissions:
  contents: write

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: robinraju/release-downloader@v1
        with:
          repository: gravitl/netclient
          tag: v0.24.3
          tarBall: true
          extract: true
      - run: mv gravitl-netclient-* netclient-src
      - uses: actions/setup-go@v5
      - working-directory: netclient-src
        run: go mod vendor
      # because actions/upload-artifact refuses to support anything but zips,
      # see https://github.com/actions/upload-artifact/issues/39 and others
      - run: tar --create --auto-compress --file netclient-0.24.3-deps.tar.xz netclient-src/vendor
      - uses: actions/upload-artifact@v4
        with:
          name: netclient-0.24.3-deps.tar.xz
          path: netclient-0.24.3-deps.tar.xz
          compression-level: 0
          if-no-files-found: error
      # if this is a tag, create new release and upload the artifacts
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          name: netclient-0.24.3
          body: This is a stub
          files: netclient-0.24.3-deps.tar.xz
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
