name: Release netclient vendor tarball
on:
  push:
    branches:
    - main
    paths:
    - 'UPSTREAM_VERSION'

permissions:
  contents: write

jobs:
  package:
    name: Release netclient vendor tarball
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: upstream-version
      run: |
        echo upstream-version=$(cat UPSTREAM_VERSION) >> $GITHUB_OUTPUT
        echo upstream-version-pep440=$(cat UPSTREAM_VERSION | cut -c2-) >> $GITHUB_OUTPUT
    - uses: robinraju/release-downloader@v1
      with:
        repository: gravitl/netclient
        tag: ${{ steps.upstream-version.outputs.upstream-version }}
        tarBall: true
        extract: true
    - run: mv gravitl-netclient-* netclient-${{ steps.upstream-version.outputs.upstream-version-pep440 }}
    - uses: actions/setup-go@v5
    - working-directory: netclient-${{ steps.upstream-version.outputs.upstream-version-pep440 }}
      run: go mod vendor
    - run: tar --create --auto-compress --file netclient-${{ steps.upstream-version.outputs.upstream-version-pep440 }}-deps.tar.gz netclient-${{ steps.upstream-version.outputs.upstream-version-pep440 }}/vendor
    - uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        name: netclient-${{ steps.upstream-version.outputs.upstream-version-pep440 }}
        body: This is a stub
        files: netclient-${{ steps.upstream-version.outputs.upstream-version-pep440 }}-deps.tar.gz
